trigger:
  - none

pool: build.zaelab.com

#Be sure to enter your value instead of "projectname" --> variables: value: projectname

variables:
  - name: project
    value: tuffshed-cpq
  - group: immersive_var

stages:
  - stage: Uninstall_deploy
    displayName: Uninstall deployment from k8s cluster
    jobs:
      - job: Uninstall_deploy
        steps:
          - bash: |
              export PATH=$PATH:/usr/local/bin
              helm version --short
              kubectl version --short --client
              export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" \
              $(aws sts assume-role \
              --role-arn $(ROLE) \
              --role-session-name AWSCLI-ADO-Session \
              --query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" \
              --output text))
              aws eks --region $(AWS_REGION) update-kubeconfig --name zc-EKS
              helm uninstall $(project) --namespace immersive

