apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.project }}-service
  namespace: immersive
spec:
  type: NodePort
  selector:
    app: {{ .Values.project }}
  ports:
    - port: {{ .Values.defaultPort }}
      targetPort: {{ .Values.defaultPort }}
